CREATE DATABASE VENTAS;

USE VENTAS;

CREATE TABLE CUSTOMER
(
    CUSTNO CHAR(8),
    CUSTFIRSTNAME VARCHAR(50),
    CUSTLASTNAME VARCHAR (50),
    CUSTCITY VARCHAR (50),
    CUSSTATE CHAR (2),
    CUSTZIP VARCHAR (50),
    CUSTBAL INT,
    CONSTRAINT CUSTNO_PK PRIMARY KEY(CUSTNO)
);

DROP TABLE CUSTOMER
CREATE TABLE EMPLOYEE
(
    EMPNO CHAR(8),
    EMPFIRSTNAME VARCHAR(50),
    EMPLASTNAME VARCHAR (50),
    EMPPHONE VARCHAR (50),
    EMPMAIL VARCHAR (50),
    CONSTRAINT EMPNO_PK PRIMARY KEY(EMPNO)
);

CREATE TABLE ORDERTBL
(
    ORDNO CHAR(8),
    ORDDATE DATE,
    CUSTNOO CHAR (8),
    EMPNO CHAR (8),
    CUSTNO CHAR (8),
    CONSTRAINT ORDNO_PK PRIMARY KEY(ORDNO)
);

ALTER TABLE ORDERTBL
ADD CONSTRAINT CUSTOMER_ORDERTBL_CUSTNO
FOREIGN KEY (CUSTNO) REFERENCES CUSTOMER (CUSTNO);

ALTER TABLE ORDERTBL
ADD CONSTRAINT EMPLOYEE_ORDERTBL_EMPNO
FOREIGN KEY (EMPNO) REFERENCES EMPLOYEE (EMPNO);


INSERT INTO CUSTOMER
    (CUSTNO, CUSTFIRSTNAME, CUSTLASTNAME, CUSTCITY, CUSTSTATE, CUSTZIP, CUSTBAL)
VALUES
    ("C0954327", "Sheri", "Gordon", "Littleton", "CO", "80129-5543", "230"),
    ("C1010398", "Jim", "Glussman", "Denver", "CO", "80111-0033", "200"),
    ("C0954327", "Sheri", "Gordon", "Littleton", "CO", "80129-5543", "230")

